apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wunero.fullname" . }}-pvc
  labels:
    {{- include "wunero.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.wunero.database.storageClass }}
  storageClassName: {{ .Values.wunero.database.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.wunero.database.size }}
