{{- if or .Values.wunero.nextauth.secret .Values.wunero.email.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wunero.fullname" . }}-secrets
  labels:
    {{- include "wunero.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.wunero.nextauth.secret }}
  nextauth-secret: {{ .Values.wunero.nextauth.secret | b64enc }}
  {{- end }}
  {{- if .Values.wunero.email.apiKey }}
  resend-api-key: {{ .Values.wunero.email.apiKey | b64enc }}
  {{- end }}
{{- end }}
